default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: studykit_development

test:
  <<: *default
  database: studykit_test

production:
  <<: *default
  database: studykit_production
  username: studykit
  password: <%= ENV['STUDYKIT_DATABASE_PASSWORD'] %>
