# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e314b95f692ba1b7c91f18a3f96ce209449761223aa29d3b81442a2ea155b51e4a2ec8ff6155ad5bd67b7b7bd782e75b627d3f3853fe192e527efab95eeb48ce

test:
  secret_key_base: 95ebb6e24747719113ab166fa39c012b412cd39b50bb342efcd6ca384e5b402d9b8d44a30dfad9c66b4e906176804c990a89901c9218269fa8d1896f8fa128f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
